### ISSUE TITLE
question: how do i use this?

### ISSUE THREAD

**Issue by byronbytes** [Cos8o/VB-RPC#1]
just... how?

**Comment by petittitouan** [comment]
Good Question,
How it works ?

**Comment by Cos8o** [comment]
it's deprecated, dont use it

**Comment by byronbytes** [comment]
> it's deprecated, dont use it

what is depreceated

**Comment by petittitouan** [comment]
An alternate ?

**Comment by Cos8o** [comment]
i don't know, sorry, i made this library as a joke :neutral_face:

**Comment by petittitouan** [comment]
Why ?

**Comment by byronbytes** [comment]
ok im back

**Comment by petittitouan** [comment]
> i don't know, sorry, i made this library as a joke 😐

But Why ?

**Comment by byronbytes** [comment]
> > i don't know, sorry, i made this library as a joke 😐
> 
> But Why ?

good question i dont know either

**Comment by byronbytes** [comment]
Lol
